repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      files: note_repo/
    # Run the formatter.
    - id: ruff-format
      files: note_repo/