services:
  app:
    hostname: app.noterepo.internal
    build:
      context: .
      dockerfile: Dockerfile
    image: note-repo:latest
    volumes:
      - ${ENVIRONMENT}/app/configs.yaml:/app/configs/configs.yaml
      - ${ENVIRONMENT}/app/.pgpass:/app/.pgpass
    environment:
      - MINIBLOG_CONFIGS_PATH=/app/configs/configs.yaml
    ports:
      - 8000:8000
    restart: always
    entrypoint: uvicorn --host 0.0.0.0 --port 8000 note_repo.main:app

  database:
    hostname: db.noterepo.internal
    image: postgres:17
    environment:
      - POSTGRES_USER=tibor
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=note_repo
    volumes:
      - db-storage:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db-storage:

secrets:
  .pgpass:
    file: .secrets/.pgpass