CREATE DATABASE note_repo WITH OWNER tibor;

\c note_repo;

CREATE TABLE IF NOT EXISTS authors (
    author_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    date_of_birth DATE
);

CREATE TABLE IF NOT EXISTS notes (
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id INTEGER REFERENCES authors (author_id),
    title TEXT NOT NULL,
    content TEXT,
    creation_date TIMESTAMP NOT NULL,
    last_update TIMESTAMP
);